[package]
name = "codechain"
version = "0.1.0"
license = "AGPL-3.0"
authors = ["Kodebox <dev@kodebox.io>"]

[dependencies]
keccak-hash = { path = "util/hash" }
log = "0.4.1"
env_logger = "0.5.3"

[[bin]]
path = "codechain/main.rs"
name = "codechain"