[package]
name = "codechain"
version = "0.1.0"
license = "AGPL-3.0"
authors = ["CodeChain Team <codechain@kodebox.io>"]

[dependencies]
app_dirs = "^1.1.1"
clap = { version = "2", features = ["yaml"] }
codechain-core = { path = "core" }
codechain-logger = { path = "logger" }
codechain-rpc = { path = "rpc" }
fdlimit = "0.1"
futures = "0.1"
log = "0.4.1"
env_logger = "0.5.3"
panic_hook = { path = "util/panic_hook" }
codechain-network = { path = "network" }
tokio-core = "0.1.6"

[[bin]]
path = "codechain/main.rs"
name = "codechain"

[workspace]
members = [
	"core",
	"crypto",
	"json",
	"keys",
	"logger",
	"network",
	"rpc"
]
