[package]
name = "codechain-types-serialize"
version = "0.2.0"
authors = ["Parity Technologies <admin@parity.io>"]
license = "MIT"
homepage = "https://github.com/paritytech/primitives"
description = "Ethereum types"

[dependencies]
serde = "1.0"
rustc-hex = "1.0"
