[package]
name = "codechain-crypto"
version = "0.1.0"
authors = ["CodeChain Team <codechain@kodebox.io>"]

[dependencies]
rust-crypto = "0.2.36"
codechain-types = { path = "../primitives/codechain-types" }

[dev-dependencies]
rand = "0.4"
